{pkgs, ...}: let
  inherit (pkgs.unstable);
in {
  environment.systemPackages = with pkgs;
    [
      unstable.neovim
      unstable.jetbrains.idea-community-bin
      rustup
      gnumake
      vim
      htop
      killall
      wget
      # required to get screen sharing to work
      (wrapFirefox (pkgs.firefox-unwrapped.override {pipewireSupport = true;})
        {})
      kitty
      wl-clipboard
      loupe
      rofi-wayland
      pavucontrol
      python3
      wezterm
      gcc13
      mpv
      gnome.nautilus
      gnome.gnome-disk-utility
      waybar
      webcord
      xwayland
      lazygit
      nodePackages_latest.typescript-language-server
      nodePackages.bash-language-server
      nodePackages.pyright
      nodePackages.eslint
      python311Packages.jedi-language-server
      tailwindcss-language-server
      prettierd
      ripgrep
      vscode-langservers-extracted
      iwgtk
      file
      grim
      slurp
      libnotify
      gammastep
      playerctl
      libimobiledevice
      ifuse
      swaybg
      util-linux
      waypaper
      jq
      lua-language-server
      stylua
      nodejs_22
      corepack_22
      pkg-config
      openssl
      android-tools
      vulkan-tools
      pinentry
      wtype
      php83Packages.composer
      nh
      hyprlock
      protonmail-bridge-gui
      thunderbird
      statix
      swaynotificationcenter
      kooha
      openjdk17-bootstrap
      rclone
      postgresql_16
      act
      solaar
      wlogout
      polkit
      polkit_gnome
      nixfmt-classic
      inetutils
      parted
      appimage-run
      pass
      shellcheck
      stripe-cli
      unrar
      unzip
      sway
      brightnessctl
      squashfsTools
      wdisplays
      flutter
      glib
      fzf
      vscodium
      pamixer
      lazysql
      cloudflared
      inkscape
      tidal-hifi
      openssl
      tmuxinator
      ngrok
      gedit
      jetbrains.pycharm-community-bin
      qemu
      dmg2img
      usbutils
      pciutils
      ranger
      virt-manager
      libvirt
      nil
      rpi-imager
      wl-color-picker
      cpulimit
      _1password-gui
      _1password
      nodePackages_latest.aws-cdk
      wev
      dnsutils
      foot
      nixd
      alejandra
    ]
    ++ lib.optionals (pkgs.system != "aarch64-linux") [
      cpufrequtils
      nvtopPackages.nvidia
      teamviewer
      onlyoffice-bin
      androidStudioPackages.canary
    ];
}
