{ pkgs, ... }:

let inherit (pkgs.unstable) ;
in {
  environment.systemPackages = with pkgs; [
    unstable.neovim
    unstable.helix
    unstable.jetbrains.idea-community-bin
    rustup
    gnumake
    vim
    htop
    killall
    wget
    # required to get screen sharing to work
    (wrapFirefox (pkgs.firefox-unwrapped.override { pipewireSupport = true; })
      { })
    kitty
    wl-clipboard
    loupe
    wofi
    pavucontrol
    python3
    wezterm
    gcc13
    mpv
    gnome.nautilus
    gnome.gnome-disk-utility
    waybar
    webcord
    xwayland
    lazygit
    nodePackages_latest.typescript-language-server
    nodePackages.bash-language-server
    nodePackages.pyright
    nodePackages.eslint
    python311Packages.jedi-language-server
    tailwindcss-language-server
    prettierd
    ripgrep
    vscode-langservers-extracted
    iwgtk
    file
    grim
    slurp
    libnotify
    gammastep
    playerctl
    libimobiledevice
    ifuse
    # chromium -> takes forever to open
    swaybg
    util-linux
    waypaper
    jq
    lua-language-server
    stylua
    nodejs_22
    corepack_22
    pkg-config
    openssl
    android-tools
    vulkan-tools
    pinentry
    wtype
    php83Packages.composer
    nh
    hyprlock
    protonmail-bridge-gui
    thunderbird
    statix
    swaynotificationcenter
    kooha
    openjdk17-bootstrap
    rclone
    postgresql_16
    act
    solaar
    wlogout
    polkit
    polkit_gnome
    nixfmt-classic
    onlyoffice-bin
    inetutils
    parted
    appimage-run
    pass
    # android-studio
    androidStudioPackages.canary
    shellcheck
    stripe-cli
    unrar
    unzip
    sway
    brightnessctl
    squashfsTools
    wdisplays
    flutter
    glib
    fzf
    vscodium
    pamixer
    lazysql
    bitwarden-cli
    cloudflared
    inkscape
    tidal-hifi
    openssl
    tmuxinator
    ngrok
    gedit
    jetbrains.pycharm-community-bin
    qemu
    dmg2img
    usbutils
    pciutils
    ranger
    nvtopPackages.nvidia
    virt-manager
    libvirt
    nil
    teamviewer
    rpi-imager
    wl-color-picker
  ];
}
