{pkgs, ...}: let
  inherit (pkgs.unstable);
in {
  environment.systemPackages = with pkgs; [
    tree-sitter # required for nvim-treesitter to work
    google-java-format
    vivify
    eclipses.eclipse-java
    java-language-server
    geteduroam
    songrec
    cmake-language-server
    glsl_analyzer
    clang-tools
    cmake
    appimage-run
    mpv
    protonvpn-gui
    volantes-cursors
    gedit
    zoxide
    pure-prompt
    findutils.locate
    tela-icon-theme

    # required for nvidia nsight graphics
    libxcb-util

    vscode-json-languageserver
    tombi
    git
    waypaper
    unstable.proton-pass
    # Tools
    pyright
    unstable.neovim # for nvim 0.12
    geteduroam-cli
    black
    gnumake
    python3
    pkg-config
    openjdk17-bootstrap
    shellcheck
    glib
    alejandra
    openssl
    ngrok
    gcc13
    nixd
    lazygit
    kitty
    lua-language-server
    stylua
    fzf
    ripgrep
    nodejs
    go
    nodePackages_latest.typescript-language-server
    nodePackages.bash-language-server
    nodePackages.eslint
    tailwindcss-language-server
    prettierd
    lua-language-server
    stylua
    corepack_22
    android-tools
    poppler-utils
    cloudflared
    vim
    htop
    wget
    loupe
    pavucontrol
    nautilus
    lazygit
    ripgrep
    file
    playerctl
    libimobiledevice
    ifuse
    util-linux
    jq
    kooha
    rclone
    act
    solaar
    polkit
    polkit_gnome
    nixfmt-classic
    inetutils
    unrar
    unzip
    squashfsTools
    fzf
    pamixer
    dmg2img
    usbutils
    pciutils
    rpi-imager
    wev
    dnsutils
    gnome-characters
    lsof
    trash-cli
    gnome-calculator
    bat
    ntfs3g
    baobab
    cpufrequtils
    ddcutil
    ddcui
  ];
}
