{
  pkgs,
  inputs,
  ...
}: {
  environment.systemPackages = with pkgs; [
    vscode-fhs
    wineWowPackages.stable
    wineWowPackages.waylandFull
    pinta
    dotnetCorePackages.sdk_8_0_3xx-bin
    geteduroam-cli
    godot-mono
    inputs.zen-browser.packages."${system}".default
    black
    obsidian
    spotify
    jellyfin-media-player
    vlc
    discord
    jetbrains.pycharm-community-bin
    ldtk
    tmuxinator
    gnumake
    python3
    pkg-config
    openjdk17-bootstrap
    shellcheck
    glib
    alejandra
    openssl
    ngrok
    gcc13
    nixd
    lazygit
    wezterm
    lua-language-server
    stylua
    fzf
    ripgrep
    rustup
    nodejs
    go
    nodePackages_latest.typescript-language-server
    nodePackages.bash-language-server
    nodePackages.eslint
    tailwindcss-language-server
    prettierd
    lua-language-server
    stylua
    corepack_22
    android-tools
    gimp3
    poppler_utils
    cloudflared
    vim
    htop
    wget
    loupe
    pavucontrol
    nautilus
    gnome-disk-utility
    lazygit
    ripgrep
    file
    playerctl
    libimobiledevice
    ifuse
    util-linux
    jq
    pinentry
    kooha
    rclone
    act
    solaar
    polkit
    polkit_gnome
    nixfmt-classic
    inetutils
    unrar
    unzip
    squashfsTools
    fzf
    pamixer
    dmg2img
    usbutils
    pciutils
    rpi-imager
    _1password-gui
    wev
    dnsutils
    gnome-characters
    lsof
    trash-cli
    gnome-calculator
    bat
    ntfs3g
    baobab
    cpufrequtils
    onlyoffice-bin
    ddcutil
    ddcui
  ];
}
