{pkgs, ...}: let
  inherit (pkgs.unstable);
in {
  # TODO: split this list into multiple and categorize
  environment.systemPackages = with pkgs;
    [
      poppler_utils
      gnumake
      vim
      htop
      wget
      wl-clipboard
      loupe
      rofi-wayland
      pavucontrol
      python3
      gcc13
      mpv
      nautilus
      gnome-disk-utility
      waybar
      xwayland
      lazygit
      nodePackages_latest.typescript-language-server
      nodePackages.bash-language-server
      nodePackages.eslint
      tailwindcss-language-server
      prettierd
      ripgrep
      iwgtk
      file
      grim
      slurp
      libnotify
      gammastep
      playerctl
      libimobiledevice
      ifuse
      swaybg
      util-linux
      jq
      lua-language-server
      stylua
      corepack_22
      pkg-config
      openssl
      pinentry
      wtype
      hyprlock
      swaynotificationcenter
      kooha
      openjdk17-bootstrap
      rclone
      postgresql_16
      act
      solaar
      wlogout
      polkit
      polkit_gnome
      nixfmt-classic
      inetutils
      parted
      appimage-run
      pass
      shellcheck
      stripe-cli
      unrar
      unzip
      sway
      brightnessctl
      squashfsTools
      wdisplays
      glib
      fzf
      vscodium
      pamixer
      lazysql
      cloudflared
      openssl
      ngrok
      gedit
      qemu
      dmg2img
      usbutils
      pciutils
      ranger
      virt-manager
      libvirt
      nil
      rpi-imager
      wl-color-picker
      cpulimit
      _1password-gui
      wev
      dnsutils
      nixd
      alejandra
      gnome-characters
      lsof
      trash-cli
      gnome-calculator
      zathura
      bat
      ntfs3g
      notesnook
      baobab
    ]
    # apps only for macbook vm
    # TODO: use hostname instead of system architecture
    ++ lib.optionals (pkgs.system == "aarch64-linux") [
      libreoffice
    ]
    # apps only for everything else except macbook vm
    # TODO: use hostname instead of system architecture
    ++ lib.optionals (pkgs.system != "aarch64-linux") [
      cpufrequtils
      onlyoffice-bin
      multipass
      ddcutil
      ddcui
    ];
}
