{pkgs, ...}: let
  inherit (pkgs.unstable);
in {
  # TODO: split this list into multiple and categorize
  environment.systemPackages = with pkgs; [
    activitywatch
    poppler_utils
    gnumake
    vim
    htop
    wget
    wl-clipboard
    loupe
    pavucontrol
    python3
    gcc13
    nautilus
    gnome-disk-utility
    lazygit
    # TODO: Move to dev
    nodePackages_latest.typescript-language-server
    nodePackages.bash-language-server
    nodePackages.eslint
    tailwindcss-language-server
    prettierd
    ripgrep
    file
    playerctl
    libimobiledevice
    ifuse
    util-linux
    jq
    lua-language-server
    stylua
    corepack_22
    pkg-config
    openssl
    pinentry
    kooha
    openjdk17-bootstrap
    rclone
    act
    solaar
    polkit
    polkit_gnome
    nixfmt-classic
    inetutils
    shellcheck
    unrar
    unzip
    squashfsTools
    glib
    fzf
    pamixer
    cloudflared
    openssl
    ngrok
    qemu
    dmg2img
    usbutils
    pciutils
    libvirt
    rpi-imager
    _1password-gui
    wev
    dnsutils
    nixd
    alejandra
    gnome-characters
    lsof
    trash-cli
    gnome-calculator
    zathura
    bat
    ntfs3g
    notesnook
    baobab
    cpufrequtils
    onlyoffice-bin
    ddcutil
    ddcui
  ];
}
